// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTeVf-69utcp8bC_rs9x9_LkVJcYtZ1o',
    appId: '1:410770524900:web:bd0088a607434cf8df7af1',
    messagingSenderId: '410770524900',
    projectId: 'merchant-7c02a',
    authDomain: 'merchant-7c02a.firebaseapp.com',
    storageBucket: 'merchant-7c02a.firebasestorage.app',
    measurementId: 'G-0KXQM4SR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeFlvs7fGyEktd1aeUuwHpLC4_o1u0ZAU',
    appId: '1:410770524900:android:d800e1fe4c423290df7af1',
    messagingSenderId: '410770524900',
    projectId: 'merchant-7c02a',
    storageBucket: 'merchant-7c02a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqULkY6xdtnEkfG7u2XsZal6Panp50eNA',
    appId: '1:410770524900:ios:87a46a1bdd844871df7af1',
    messagingSenderId: '410770524900',
    projectId: 'merchant-7c02a',
    storageBucket: 'merchant-7c02a.firebasestorage.app',
    iosBundleId: 'com.example.merchandiserWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqULkY6xdtnEkfG7u2XsZal6Panp50eNA',
    appId: '1:410770524900:ios:87a46a1bdd844871df7af1',
    messagingSenderId: '410770524900',
    projectId: 'merchant-7c02a',
    storageBucket: 'merchant-7c02a.firebasestorage.app',
    iosBundleId: 'com.example.merchandiserWeb',
  );
}
